#!/bin/bash

##SBATCH --chdir=
#SBATCH --job-name=dgen
#SBATCH --output=job.%j.out
#SBATCH --ntasks=5
#SBATCH --cpus-per-task=30
 
export SINGULARITY_LOCALCACHEDIR=`pwd`/tmp
export SINGULARITY_TMPDIR=`pwd`/tmp
mkdir -p $SINGULARITY_TMPDIR
set -xe
module load singularity || true

rm -rf cfg/tmp/*
rm -rf results
rm -rf tmp

srun -n 5 singularity exec $HOME/sifs/hlsix-220922.sif /opt/conda/envs/torch/bin/python3 train.py


echo 'Finished on ' `date`
